# Generated by Django 4.1 on 2022-11-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=13)),
                ('flag_ativo', models.BooleanField(default=True)),
                ('lavagens', models.IntegerField(default=0)),
                ('consertos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=4)),
                ('placa', models.CharField(max_length=8)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img')),
                ('imagem_original', models.ImageField(blank=True, null=True, upload_to='img_original')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.CharField(choices=[('M', 'Mecanico'), ('L', 'Lavagem')], max_length=1)),
                ('descricao', models.CharField(max_length=255)),
                ('data_abertura', models.DateTimeField()),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('ods', models.CharField(max_length=10)),
                ('preco', models.FloatField(blank=True, null=True)),
                ('imagem_final', models.ImageField(blank=True, null=True, upload_to='img_final')),
                ('flag_ativo', models.BooleanField(default=True)),
                ('combinar_preco', models.BooleanField(default=False)),
                ('veiculo', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.veiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.CharField(choices=[('M', 'Mecanico'), ('L', 'Lavagem')], max_length=1)),
                ('descricao', models.CharField(max_length=255)),
                ('data_abertura', models.DateTimeField()),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('ods', models.CharField(max_length=10)),
                ('preco', models.FloatField(blank=True, null=True)),
                ('imagem_final', models.ImageField(blank=True, null=True, upload_to='img_final')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.veiculos')),
            ],
        ),
    ]
