# Generated by Django 4.1 on 2022-09-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagem',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
