# Generated by Django 4.1 on 2022-09-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_pedido_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_abertura',
            field=models.DateField(auto_now_add=True),
        ),
    ]
