# Generated by Django 4.1 on 2023-02-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_pedido_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='consertos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='lavagens',
        ),
    ]
