# Generated by Django 4.1 on 2022-09-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_pedido_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
