# Generated by Django 4.1 on 2022-09-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='preco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
