# Generated by Django 4.1 on 2022-09-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_pedido_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='flag_ativo',
            field=models.BooleanField(default=False),
        ),
    ]
