# Generated by Django 4.1 on 2022-09-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_pedido_flag_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='flag_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
