# Generated by Django 4.1 on 2022-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_pedido_flag_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
