# Generated by Django 4.1 on 2022-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_pedido_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='combinar_preco',
            field=models.BooleanField(default=False),
        ),
    ]
