# Generated by Django 4.1 on 2022-09-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_pedido_combinar_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_abertura',
            field=models.DateTimeField(),
        ),
    ]
