# Generated by Django 4.1 on 2022-09-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_alter_pedido_data_abertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='imagem',
        ),
        migrations.AddField(
            model_name='pedido',
            name='imagem_final',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
