# Generated by Django 4.1 on 2022-09-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_remove_pedido_imagem_pedido_imagem_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='imagem',
            field=models.ImageField(upload_to='img'),
        ),
    ]
