# Generated by Django 4.1 on 2022-09-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_alter_veiculos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='imagem_final',
            field=models.ImageField(blank=True, null=True, upload_to='img_final'),
        ),
    ]
